### ISSUE TITLE
APP_URL is ignored and assets (stylesheets and javascript) are not loading

### ISSUE THREAD

**Issue by alexmocanu** [barryvdh/laravel-debugbar#1575]
I've managed to reproduce this on a fresh laravel 11 install:

Installed Laravel 11:
composer create-project laravel/laravel:^11.0

In .env i've set the following:
APP_DEBUG=true
APP_URL=http://localhost:8900/testl/public --- my local server runs on port 8900 and I installed laravel in /testl

I installed the debug bar:
composer require barryvdh/laravel-debugbar --dev
php artisan vendor:publish --provider="Barryvdh\Debugbar\ServiceProvider"

The debug bar is ignoring the APP_URL variable and assets are not loading (it tries to load them from the root):

Screenshot:
![test_failure](https://github.com/barryvdh/laravel-debugbar/assets/834418/1bfae8d0-6164-4617-bb94-7bc92c551b0e)

Composer and env files (had to use the txt extension - github won't let me upload them otherwise):
[env.txt](https://github.com/barryvdh/laravel-debugbar/files/14587901/env.txt)
[composer.json](https://github.com/barryvdh/laravel-debugbar/files/14587903/composer.json)
[composer.lock.txt](https://github.com/barryvdh/laravel-debugbar/files/14587907/composer.lock.txt)

The issue started appearing with v3.11.0. Installing v3.10 fixes the problem for me

**Comment by erikn69** [comment]
Maybe related to #1562

**Comment by parallels999** [comment]
The normal thing is to configure a virtual host to avoid these problems
```cnf
<VirtualHost *>
  DocumentRoot "C:\laravel\testl\public"
  ServerName laravel.localhost
  Header set Access-Control-Allow-Credential true
  <Directory "C:\laravel\testl\public">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
  </Directory>
</VirtualHost>
```
So, your path is like `http://laravel.localhost`

**Comment by alexmocanu** [comment]
> > my local server runs on port 8900 and I installed laravel in /testl
> 
> The normal thing is to configure a virtual host to avoid these kind problems
> 
> ```ini
> <VirtualHost *:8900>
>   DocumentRoot "C:\laravel\testl\public"
>   ServerName laravel.localhost
>   Header set Access-Control-Allow-Credential true
>   <Directory "C:\laravel\testl\public">
>     Options Indexes FollowSymLinks
>     AllowOverride All
>     Require all granted
>   </Directory>
> </VirtualHost>
> ```
> 
> So, your url is like `http://laravel.localhost` [laradock/laradock/apache2/sites/sample.conf.example](https://github.com/laradock/laradock/blob/581649752536a9d63f42e481cdc1a85e1dd2bad4/apache2/sites/sample.conf.example)

I agree and using a vhost land pointing some fake domain to it in the /etc/hosts file would have been easy, but due to some weird internal company policies my current workstation is locked down and I can't do that. 

For now I downgraded to version 3.10, which loads the debug bar's assets correctly regardless of url.

**Comment by adriweb** [comment]
Same issue here still on Laravel 10.x (latest so far). It seems to be due to https://github.com/barryvdh/laravel-debugbar/pull/1562 which forces relative URLs somehow? I'm not sure.

FWIW, my laravel app/website is on a subdirectory on the apache server, and `APP_URL` is correctly set in the `.env` file.

**Comment by alexmocanu** [comment]
Something like this in JavascriptRenderer.php should solve the issue:

```php
$cssRoute = route('debugbar.assets.css', [
    'v' => $this->getModifiedTime('css'),
    'theme' => config('debugbar.theme', 'auto'),
]);

$jsRoute = route('debugbar.assets.js', [
    'v' => $this->getModifiedTime('js')
]);

$cssRoute = parse_url($cssRoute, PHP_URL_PATH);
$jsRoute = parse_url($jsRoute, PHP_URL_PATH);
```
It should build the URLs with the complete relative paths, regardless of where laravel is hosted and remove the domain name part at the same time.

**Comment by sakihl** [comment]
Thanks @alexmocanu 
I was just about to try to copy the change in https://github.com/barryvdh/laravel-debugbar/pull/1555 when I realised that my source file was a later version including https://github.com/barryvdh/laravel-debugbar/pull/1562 and therefore the code didn't match. I have tried your suggested change to  JavascriptRenderer.php instead and it seems to have fixed the problem. My console errors have disappeared and the debugbar is showing. I hope your suggestion has no unwanted side-effects and can become a fix.

**Comment by erikn69** [comment]
`parse_url($cssRoute, PHP_URL_PATH);` cuts the query part, https://github.com/barryvdh/laravel-debugbar/pull/1555 is a better option

**Comment by swartjie** [comment]
Has this been patched?
It seems to still happen on the installation I did about 5 hours ago...

**Comment by swartjie** [comment]
@barryvdh working like a charm. Thank you!

**Comment by nafiesl** [comment]
@barryvdh dev-master works for me as well. (laravel 11)
