### ISSUE TITLE
not showing up in laravel spark

### ISSUE THREAD

**Issue by vesper8** [barryvdh/laravel-debugbar#492]
This might just be my own blindness but I've been scratching my head for an hour on this.

Followed the installation procedure, published everything.

Oddly, the /storage/debugbar/ did not get autocreated, had to create it manually.

On page refreshes, new .json files are being added to that folder now. But I can't get anything to show up in the browser. I've even tried selling the "enabled" flag from null to true. My .env app_debug is also true.

Any idea?

**Comment by vesper8** [comment]
seems like this may be related to route caching and fixed in #484

However it's weird because other people are using Spark and not having this problem. And I have tried repeatedly clearing the route cache (and all other caches). Literally this:

```
composer dump-auto
php artisan clear-compiled
php artisan config:cache
php artisan route:cache
php artisan cache:clear
php artisan view:clear
php artisan debugbar:clear
rm storage/logs/*.log
rm storage/framework/sessions/*
```

And nothing I do makes the routes show up.

**Comment by MacWorks** [comment]
I've followed the instructions for installing it, checked the config, tried forcing it on, dumbed down my default template, created the same storage folder and it does spit out json files there, but I don't see the debug bar at all. I'm using Laravel 5.1. It doesn't seem to be injecting.

Do I need to move assets into my public folder? If so that's not mentioned in the installation instructions. So confused, about to give up on it.

**Comment by wayneashleyberry** [comment]
I've run into the same issue, but I'm not using Spark. I think it has something to do with have a dynamic route path at the base of the url... eg.

```php
Route::get('/{foo}', 'FooController@foo');
```

I have a lot of these routes in a project I'm working on and if I disable them Debug Bar appears.

**Comment by wayneashleyberry** [comment]
Just figured it out, not sure if this will help anyone else... but make sure `Barryvdh\Debugbar\ServiceProvider::class,` is **above** any other providers that register routes.

**Comment by sparkison** [comment]
Any updates on this one? I'm still not seeing debugbar in the main Spark app pages. Looks like it has to do specifically with this code, added by Spark in the main app layout file:

```PHP
<script>
        window.Spark = <?php echo json_encode(array_merge(
            Spark::scriptVariables(), []
        )); ?>;
</script>
```

Debugbar shows on any page outside of the app, but as soon as the main layout loads it chokes and gets a 500 error. Also tried doing as @wayneashleyberry suggested without success.
